---
  - name:
    hosts: localhost
    tasks:
      - name: Install Software htop
        apt:
          name: htop
          state: latest
      - name: Install Software Git 
        apt:
          name: git
          state: latest
      - name: Update
        apt:
          name: update
      - name: upgrade
        apt:
          name: upgrade
