---
  - name:
    hosts: localhost
    tasks:
      - name: Install Software htop
        apt:
          name: htop
          state: latest
          
      - name : install Node and NPM
        apt:
           name: nodejs
           state: latest
      - name : SoftwarePackage 
        apt:
           name: apache2
                - xorriso
                - squashfs-tools
                - debootstrap
                - mtools
                - grub-pc-bin
                - grub-efi-amd-bin
           state: latest
