---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo
      apt:
        update_cache: yes
      change_when: False

  tasks:
    - include: tasks/packages.yml
