---
  - name:
    hosts: localhost
    tasks:
      - name: Install Software htop
        apt:
          name: htop
          state: latest
          
      - name : install Node and NPM
        apt:
           name: nodejs
           state: latest
