---
  - name: Software test
    hosts: localhost
    tasks:

      - name: Install Software htop
        apt:
          name: htop
          state: latest

      - name : install Node and NPM
        apt:
           name: nodejs
           state: absent

      - name : SoftwarePackage
        apt:
           name: apache2
           state: latest
      
      - name: Install docker
        apt:
          name: docker.io
          state: latest
      
      - name: Run Docker with nextcloud
        shell: "docker stop -d -p 8080:80 nextcloud"
