---
  - name:
    hosts: CL
    tasks:
      - name: Install Software git &
        apt:
          name: git
          state: latest

    tasks:
       - name: git clone
         git:
           name: clone
           repo: git@github.com:Cyberhost-itservice/cyberhost_ansible_pull.git
           dest: "/home/repo
