---
  - name: Software test
    hosts: localhost
    tasks:

      - name: Install Software htop
        apt:
          name: htop
          state: absent

      - name : install Node and NPM
        apt:
           name: nodejs
           state: absent

      - name : SoftwarePackage
        apt:
           name: apache2
           state: absent


      - name: Upgrade all Pckg
        apt:
          name: "*"
          state: latest
          update_cache: yes
      
      - name: Install docker
        apt:
          name: docker.io
          state: absent
      
#      - name: Run Docker with nextcloud
#        shell: "docker run -d -p 8080:80 nextcloud"
