#https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html

# mnt folder create
- name: mkdir folder proc sys dev
  command: 
     mkdir /mnt/proc
     mkdir /mnt/sys
     mkdir /mnt/dev
     mkdir /mnt/dev/pts
     mkdir /mnt/boot
     mkdir /mnt/boot/efi

# mount the system 
- name: mount the files in mnt...
  command: 
     mount -t proc proc /mnt/proc
     mount -o bind /sys /mnt/sys
     mount -o bind /dev /mnt/dev
     mount -o bind /dev/pts /mnt/dev/pts



- name: Mount Proc
  mount:
    path: /mnt/proc
    src: /dev/proc
#    fstype: iso9660
    opts: ro,noauto
    state: present


