- name: Remove all partitions from disk
  parted:
    device: /dev/vda1
#    device: /dev/vda2
    number: 1
    state: absent
#  loop: '{{ vda_info.partitions }}'

- name: Create a new Boot primary partition
  parted:
    device: /dev/vda
    number: 1
    state: present
#    flags: [ fat32 ]
#    fs_type: ext2
    part_end: 1GB        

- name: Create a new EFI primary partition
  parted:
    device: /dev/vda
    number: 2
    state: present
#    fs_type: fat32
    part_start: 1GB
    part_end: 2GB

- name: Create Filesystem with LVM
  parted:
    device: /dev/vda
    number: 3
    flags: [ lvm ]
    state: present
#    fs_type: ext4
    part_start: 2GB
#    part_end: 15GB 

#- name: create container if it does not exist and add new key to it
#  luks_device:
#    device: "/dev/vda3"
#    state: "present"
#    keyfile: "/vault/key"
#    new_keyfile: "/vault/keyfile2"

#this function
#- name: Create LuksFormat
#  shell: 
#     cmd: cryptsetup -q luksFormat /dev/vda3
#     stderr_lines: 123asd

# - name: install boot loader (grub)
#  command: grub-install /dev/vda1
#  with_items: "{{ layout }}"
#  when: not item['skip_grub']|default(False)

- name: Install BOotloader TEST2 
  command: apt install grub-efi-amd64-signed /dev/vda2
  command: apt update
